{{- if .Values.prometheus.create }}

  {{- if .Values.rbac.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.prometheus.serviceAccount }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-chaos-prometheus
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-chaos-prometheus
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.serviceAccount }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-chaos-prometheus
  apiGroup: rbac.authorization.k8s.io

  {{- end }}

{{- end }}
