{{- if .Values.prometheus.create }}

apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: chaos-prometheus
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  selector:
    {{- include "chaos-mesh.selectors" . | nindent 4 }}
    app.kubernetes.io/component: prometheus

{{- end }}
