apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: io-delay-example
spec:
  schedule: '@every 10m'
  type: IOChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  ioChaos:
    action: latency
    mode: one
    path: /var/run/etcd/**/*
    selector:
      labelSelectors:
        app: etcd
    volumePath: /var/run/etcd
    delay: 100ms
    percent: 50
    duration: 400s
