apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: web-show-pod-failure
spec:
  schedule: '@every 2m'
  type: PodChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-failure
    mode: one
    duration: 30s
    selector:
      namespaces:
      - default
      labelSelectors:
        app: web-show
