apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: jvm-exception-example
  namespace: app
spec:
  schedule: '@every 1m'
  type: JVMChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  jvmChaos:
    action: tce
    target: jvm
    flags:
      exception: java.lang.Exception
    matchers:
      classname: org.chaosmesh.jvm.Application
      methodname: hello
    mode: one
    selector:
      labelSelectors:
        app: springboot-jvmchaos-demo
    duration: 30s
