apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: jvm-oom-example
  namespace: app
spec:
  schedule: '@every 1m'
  type: JVMChaos
  historyLimit: 5
  concurrencyPolicy: Forbid
  jvmChaos:
    action: oom
    target: jvm
    flags:
      area: HEAP
      wild-mode: "true"
    mode: one
    selector:
      labelSelectors:
        app: springboot-jvmchaos-demo
    duration: 30s
