apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-example
  namespace: chaos-testing
spec:
  action: container-kill
  mode: one
  selector:
    labelSelectors:
      app.kubernetes.io/component: monitor
  containerNames:
  - prometheus
