apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-duplicate-example
  namespace: chaos-testing
spec:
  action: duplicate
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  duplicate:
    duplicate: "40"
    correlation: "25"
  duration: "10s"
