apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - web
    labelSelectors:
      "app.kubernetes.io/component": "web-app"
  delay:
    latency: "90ms"
    correlation: "25"
    jitter: "90ms"
  direction: to
  target:
    selector:
      namespaces:
        - db
        - storage
      labelSelectors:
        "app.kubernetes.io/component": "pool"
    mode: one
  duration: "10s"
